truncate table gedi_migration_equipments RESTART IDENTITY;
truncate table gedi_migration_infractions RESTART IDENTITY;
truncate table gedi_migration_nas RESTART IDENTITY;
truncate table gedi_migration_vehicles RESTART IDENTITY;
truncate table gedi_migration_violator_addresses RESTART IDENTITY;
truncate table gedi_migration_violators RESTART IDENTITY;